// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjujL61syFAvHtXz9jmP8-btIhcdZcyOI',
    appId: '1:107010768252:web:229877f1d2aeaf37f538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    authDomain: 'sistem-academic.firebaseapp.com',
    storageBucket: 'sistem-academic.appspot.com',
    measurementId: 'G-G6BPHHT4MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFNAxRwisuzE_lQhvKzXONBhxFLEVmCRM',
    appId: '1:107010768252:android:188c7cdd73e12a4df538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    storageBucket: 'sistem-academic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmhgKgqafEZLsw0rB6SOAqX3yD9cyudSg',
    appId: '1:107010768252:ios:fe3d2949d25706fff538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    storageBucket: 'sistem-academic.appspot.com',
    iosBundleId: 'com.example.academicMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmhgKgqafEZLsw0rB6SOAqX3yD9cyudSg',
    appId: '1:107010768252:ios:fe3d2949d25706fff538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    storageBucket: 'sistem-academic.appspot.com',
    iosBundleId: 'com.example.academicMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjujL61syFAvHtXz9jmP8-btIhcdZcyOI',
    appId: '1:107010768252:web:35a0a400012da733f538f9',
    messagingSenderId: '107010768252',
    projectId: 'sistem-academic',
    authDomain: 'sistem-academic.firebaseapp.com',
    storageBucket: 'sistem-academic.appspot.com',
    measurementId: 'G-HYWFCZEMYH',
  );

}